name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 5b97d724-9892-4d56-91b8-f532327ff463
          heroku_app_name: snax90tuy
          heroku_email: zheqqqwkvenfwon@scpulse.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_CONFIG_FILE_URL: https://gist.githubusercontent.com/Snax-phycho/b2d6baeb159527ca2d1f1f504d4957f0/raw/Config.env
